---
title: "Homework 3"
author: "Samantha Rutledge"
date: "10/13/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

## Question 1

```{r}
set.seed(12) # to be reproducible
A = matrix(data = runif(n = 1:500), nrow = 50, ncol = 10)
colnames(A) = paste("lake", 1:10, sep = "_")
```
```{r}
colMeans(A)
```

```{r}
for(i in 1:ncol(A)){
  print(mean(A[, i]))
}
```

## Question 2
```{r}
x = array(1:27, dim = c(3, 3, 3))
x
apply(X = x, MARGIN = c(1, 2), 
      FUN = paste, collapse = ", ")
```
```{r}
for(i in 1:5)
{
for(j in 1:2)
{
print(i*j);
}
}
```

## Question 3

```{r}
fib_value[1] <- 0
fib_value[2] <- 1
for(i in 3:30){fib_value[i] <- fib_value[i-1]+fib_value[i-2]}
print(fib_value)
```

## Question 4
```{r}
top105 = readLines("http://www.textfiles.com/music/ktop100.txt")
top105 = top105[-c(64, 65)] # missing No. 54 and 55
```

```{r}
x<-c(str_extract(top105,"^\\d{1,5}\\.+"))
x
```
```{r}
x<-c(str_extract(top105,"^[^A-Z]{1,5}\\.\\d+"))
x
```
```{r}
x<-c(str_extract(top105,"^[^A-Z]{1,5}\\.\\d?+"))
x
```
```{r}
x<-c(str_extract(top105,"^[^A-Z]{1,5}\\.\\d?+"))
y <- c(na.omit(x))
y
```
Question 5
```{r}
z<- gsub('\\.$', '', y)
z
```
```{r}
v <-as.numeric(z)
v
```
```{r}
duplicated(v)
v[duplicated(v)]
```


