# workflow_demo

The purpose of this repository is to document - from data to final manuscript - a case study investigating the taxonomic and geographic representation given by salvaged and actively collected museum ornithological specimens. Included within are the workflow (data source, cleaning, wrangling, visualization, and analysis), final figures/tables, a license file for the code within, and the raw and output datasets.

This repository has the following file folders:

- `Data`: raw and output datasets are contained within
- `R`: all R codes are contained within
- `Figs`: all figures generated by R codes are within
- `Doc`: all manuscripts are within

Some prerequires:

- `GNU Make`: to document file dependencies and automate workflow. In terminal, you can just type `make` to render the rmarkdown file to pdf and html.
- `R`: for data clean and analyses.
- `LaTeX`: for fine control of typesetting and pdf generation. Recommend to use [`tinytex`](https://yihui.org/tinytex/).
- `Pandoc`: for file types converting, e.g. convert markdown file to pdf or docx files or html files.
	+ if you have `Rstudio` installed, you can also use pandoc shipped with Rstudio

## Data/code Usage
Please contact author at srutle6@lsu.edu if interested in utilizing data and/or code within repository
