---
title: "Rutledge_SL_final_project"
output: html_document
---
```{r}
### load libraries ###
library(tidyverse)
```

```{r}
### load appropriate libraries
library(tidyverse)
```


```{r}
### Identify unknown/blank collecting methods ###
Arctos_birds_Calif_2000_2020$coll_method_2 <- ifelse(is.na(Arctos_birds_Calif_2000_2020$collecting_method), "unknown","known")
```


```{r}
###Identify rows as salvage based on collectors, parts, and spec_locality ###
Arctos_birds_Calif_2000_2020$coll_method_4[Arctos_birds_Calif_2000_2020$coll_method_2 == "unknown" &
                                             grepl("^[0-9]+", Arctos_birds_Calif_2000_2020$spec_locality, ignore.case = T) &
                                             !grepl(" mi | km | block | m | yds ", Arctos_birds_Calif_2000_2020$spec_locality, 
                                                    ignore.case = T)] = "salvage"

### ACTUAL CHUNK ###
Arctos1 <- Arctos_birds_Calif_2000_2020 %>% mutate(coll_method_4 = ifelse(coll_method_2 == "unknown" & grepl("^[0-9]+", spec_locality, ignore.case = T) & !grepl(" mi | km | block | m | yds ", spec_locality, ignore.case = T), "salvage", "unknown"))

---------------------------------------------------------------


Arctos_birds_Calif_2000_2020$coll_method_3 = ifelse(Arctos_birds_Calif_2000_2020$coll_method_2 == "unknown" & is.na(Arctos_birds_Calif_2000_2020$collectors), "salvage", ifelse(Arctos_birds_Calif_2000_2020$coll_method_2 == "unknown" & Arctos_birds_Calif_2000_2020$parts %in% c(grep("^skull\\w*", Arctos_birds_Calif_2000_2020$parts, value=T)), "salvage", ifelse(Arctos_birds_Calif_2000_2020$coll_method_2 == "unknown" & Arctos_birds_Calif_2000_2020$spec_locality %in% c(grep("highway|hwy", Arctos_birds_Calif_2000_2020$spec_locality, ignore.case = T, value = T)),"salvage", ifelse(Arctos_birds_Calif_2000_2020$coll_method_4 == "salvage", "salvage", 0))))

### ACTUAL CHUNK ###
Arctos2 <- Arctos1 %>% mutate(coll_method_3 = ifelse(coll_method_2 == "unknown" & is.na(collectors), "salvage", ifelse(coll_method_2 == "unknown" & parts %in% c(grep("^skull\\w*", parts, value=T)), "salvage", ifelse(coll_method_2 == "unknown" & spec_locality %in% c(grep("highway|hwy", spec_locality, ignore.case = T, value = T)),"salvage", ifelse(coll_method_4 == "salvage", "salvage", "unknown")))))
```

```{r}
### now remove some bits ###
df <- Arctos2 %>% filter(!(parts=="egg" | parts  =="egg; nest" | parts == "nest; egg" | parts == "media; egg"))
df2 <- df %>% filter(!(parts=="blood" | parts  =="blood; blood" | parts == "blood; blood; blood" | parts == "blood; blood; blood; blood"))
```
```{r}
###Look at what's left
df_still_unknown <- df2 %>% filter(coll_method_2 == "unknown")
```

```{r}
df_still_unknown_2 <- df2 %>% filter(is.na(coll_method_3)&coll_method_2 == "unknown")
```


```{r}
### remove entries with parts "unknown" or "nest", as well as age "embryo" or "chick"
df3 <- df2 %>% filter(!(parts=="nest" | parts  =="unknown"))
df4 <- df3 %>% filter(!(age == "embryo" | age == "chick" | age == "downy chick" | age == "downy chick, completely covered in fuzz, eyes still closed" | age == "naked chick, eyes closed" | age == "downy chick, fuzz on body, eyes not open" | age == "downy chick, pre-fledge" | age == "downy fledgling" | age == "not yet fully fledged, still downy" | age == "skull unossified, downy (only slightly fuzzy on head & backside of the body" | age == "skull unossified, naked & downy (some fuzz on head and backside, eyes still closed)" | age == "skull unossified, transitioning from naked to downy, eyes closed" | age == "skull unossified, downy, eyes closed" | age == "skull unossified, between naked and downy (some fuzz on head and backside, eyes still closed)")) 
```

```{r}
### Again, look at what is left
df_still_unknown_3 <- df4 %>% filter(is.na(coll_method_3)&coll_method_2 == "unknown")

### reassigning tissues as salvage? exploring what's left...
df_still_unknown_4 <- df_still_unknown_3 %>% filter(!(parts == "tissue" | parts == "tissue; tissue sample" | parts == "wing; tissue"))
df_still_unknown_5 <- df_still_unknown_4 %>% filter(!(spec_locality == "Aviary in Oakland" | spec_locality == "aviary of Monica J. Albe, Oakland" | spec_locality == "San Diego Zoo" | spec_locality == "CAPTIVE, San Diego Zoo [probably]" | spec_locality == "CAPTIVE, San Diego Zoo" | spec_locality == "San Francisco Zoo, San Francisco" | spec_locality == "Zoological Society of San Diego" | spec_locality == "Zoological Society of San Diego, CAPTIVE" | spec_locality == "CAPTIVE Zoological Societ of San Diego" | spec_locality == "CAPTIVE Zoological Society of San Diego" | spec_locality == " San Diego: Sea World CAPTIVE" | spec_locality == "Amador High School, 1155 Santa Rita Rd., Pleasanton" | spec_locality == "Pittsburg High School, Pittsburg" | spec_locality == "no specific locality recorded" | spec_locality == "unknown" | spec_locality == "Life Sciences Building courtyard, University of California campus, Berkeley" | spec_locality == "Natural Resources Building, Mineral" | spec_locality == "Outside Earth and Marine Sciences Building, University of California, Santa Cruz" | spec_locality == "near south door of Valley Life Sciences Building, University of California campus, Berkeley" | spec_locality == "near Protein Design Labs (34801 Campus Drive), near Dumbarton Bridge, Fremont" | spec_locality == "W side of Dwinelle Hall, Univ. Calif. campus, Berkeley" | spec_locality == "in vicinity of breezeway between Birge and LeConte Halls, University of California campus, Berkeley" | spec_locality == "Stadium Rim Way between Centennial Rd. and Galey Rd., University of California campus, Berkeley" | spec_locality == "University of California campus, Berkeley" | spec_locality == "University of California Riverside campus, Riverside" | spec_locality == "north side of Hildebrand Hall, University of California campus, Berkeley" | spec_locality == "east side of Lewis Hall, University of California Berkeley campus" |spec_locality == "Unit 2 Dormitory, between Channing and Haste Streets, Berkeley" | spec_locality == "Strawberry Creek Lodge (1320 Addison Street), Berkeley" | spec_locality == "Davis" | spec_locality == "University of California Botanical Garden, Strawberry Canyon, Berkeley" | spec_locality == "Berkeley" | spec_locality == "Life Sciences Addition, University of California, Berkeley" | spec_locality == "Donner Lab, University of California, Berkeley" | spec_locality == "California Hall, University of California, Berkeley" | spec_locality == "Women's Faculty Club, University of California, Berkeley" | spec_locality == "Linsdale Library, Hastings Natural History Reservation" | spec_locality == "San Rafael, 24 Madrona Street" | spec_locality == "San Diego: Sea World CAPTIVE" | spec_locality == "Edwards AFB" | spec_locality == "classroom at Hastings Natural History Reservation" | spec_locality == "labs at Hastings Natural History Reservation, Carmel Valley" | spec_locality == "Lawrence Livermore National Lab" | spec_locality == "outside the Davis Lab, Hastings Natural History Reservation, Carmel Valley" | spec_locality == "Sacramento" | spec_locality == "El Cerrito" | spec_locality == "Ojai" | spec_locality == "Livermore" | spec_locality == "Inverness" | spec_locality == "Bolinas" | spec_locality == "Oakland" | spec_locality == "Pittsburg" | spec_locality == "Pleasant Valley" | spec_locality == "Bethel Island" | spec_locality == "Woodacre" | spec_locality == "Jamesburg" | spec_locality == "Nicasio" | spec_locality == "La Casa de Maria, 801 Ladera Lane, Santa Barbara" | spec_locality == "Anaheim" | spec_locality == "Pt. Mugu Naval Base, Air National Guard hanger" | spec_locality == "Carmel Valley" | spec_locality == "Hopland Research and Extension Center bunkhouse" | spec_locality == "Wildlife Gallery, Bolinas" | spec_locality == "Alameda Naval Station, Alameda" | spec_locality == "Mills College, Oakland"))
```


```{r}
### assigning salvage based on parts
df4$coll_method_5 <- ifelse(df4$parts=="tissue" | df4$parts == "tissue; tissue sample" | df4$parts == "wing; tissue", "salvage", "unknown")


### ACTUAL CHUNK
df41 <- df4 %>% mutate(coll_method_5 = ifelse(df4$parts=="tissue" | df4$parts == "tissue; tissue sample" | df4$parts == "wing; tissue", "salvage", "unknown"))
```


```{r}
### actual df5; assigning salvage based on locality
df51 <- df41 %>% 
    mutate(coll_method_6 = ifelse(spec_locality == "Aviary in Oakland" | spec_locality == "aviary of Monica J. Albe, Oakland" | spec_locality == "San Diego Zoo" | spec_locality == "CAPTIVE, San Diego Zoo [probably]" | spec_locality == "CAPTIVE, San Diego Zoo" | spec_locality == "San Francisco Zoo, San Francisco" | spec_locality == "Zoological Society of San Diego" | spec_locality == "Zoological Society of San Diego, CAPTIVE" | spec_locality == "CAPTIVE Zoological Societ of San Diego" | spec_locality == "CAPTIVE Zoological Society of San Diego" | spec_locality == " San Diego: Sea World CAPTIVE" | spec_locality == "Amador High School, 1155 Santa Rita Rd., Pleasanton" | spec_locality == "Pittsburg High School, Pittsburg" | spec_locality == "no specific locality recorded" | spec_locality == "unknown" | spec_locality == "Life Sciences Building courtyard, University of California campus, Berkeley" | spec_locality == "Natural Resources Building, Mineral" | spec_locality == "Outside Earth and Marine Sciences Building, University of California, Santa Cruz" | spec_locality == "near south door of Valley Life Sciences Building, University of California campus, Berkeley" | spec_locality == "near Protein Design Labs (34801 Campus Drive), near Dumbarton Bridge, Fremont" | spec_locality == "W side of Dwinelle Hall, Univ. Calif. campus, Berkeley" | spec_locality == "in vicinity of breezeway between Birge and LeConte Halls, University of California campus, Berkeley" | spec_locality == "Stadium Rim Way between Centennial Rd. and Galey Rd., University of California campus, Berkeley" | spec_locality == "University of California campus, Berkeley" | spec_locality == "University of California Riverside campus, Riverside" | spec_locality == "north side of Hildebrand Hall, University of California campus, Berkeley" | spec_locality == "east side of Lewis Hall, University of California Berkeley campus" |spec_locality == "Unit 2 Dormitory, between Channing and Haste Streets, Berkeley" | spec_locality == "Strawberry Creek Lodge (1320 Addison Street), Berkeley" | spec_locality == "Davis" | spec_locality == "University of California Botanical Garden, Strawberry Canyon, Berkeley" | spec_locality == "Berkeley" | spec_locality == "Life Sciences Addition, University of California, Berkeley" | spec_locality == "Donner Lab, University of California, Berkeley" | spec_locality == "California Hall, University of California, Berkeley" | spec_locality == "Women's Faculty Club, University of California, Berkeley" | spec_locality == "Linsdale Library, Hastings Natural History Reservation" | spec_locality == "San Rafael, 24 Madrona Street" | spec_locality == "San Diego: Sea World CAPTIVE" | spec_locality == "Edwards AFB" | spec_locality == "classroom at Hastings Natural History Reservation" | spec_locality == "labs at Hastings Natural History Reservation, Carmel Valley" | spec_locality == "Lawrence Livermore National Lab" | spec_locality == "outside the Davis Lab, Hastings Natural History Reservation, Carmel Valley" | spec_locality == "Sacramento" | spec_locality == "El Cerrito" | spec_locality == "Ojai" | spec_locality == "Livermore" | spec_locality == "Inverness" | spec_locality == "Bolinas" | spec_locality == "Oakland" | spec_locality == "Pittsburg" | spec_locality == "Pleasant Valley" | spec_locality == "Bethel Island" | spec_locality == "Woodacre" | spec_locality == "Jamesburg" | spec_locality == "Nicasio" | spec_locality == "La Casa de Maria, 801 Ladera Lane, Santa Barbara" | spec_locality == "Anaheim" | spec_locality == "Pt. Mugu Naval Base, Air National Guard hanger" | spec_locality == "Carmel Valley" | spec_locality == "Hopland Research and Extension Center bunkhouse" | spec_locality == "Wildlife Gallery, Bolinas" | spec_locality == "Alameda Naval Station, Alameda" | spec_locality == "Mills College, Oakland", "salvage", "unknown"))
```

```{r}
### Assigning as salvage based on collecting method
### First, deal with NAs
df6 <- df51 %>% mutate(coll_NAs = ifelse(is.na(collecting_method), "unknown", "known"))
df6$collecting_method[is.na(df6$collecting_method)] <- 0

df7 <- df6 %>% 
    mutate(coll_method_7 = ifelse(collecting_method == "dead on road" | collecting_method == "died on barbed wire fence" | collecting_method == "euthanized" | collecting_method == "euthanized while at Wetlands and Wildlife Care Center" | collecting_method == "euthanized while at WWCC" | collecting_method == "found injured and transferred to WWCC where euthanized" | collecting_method == "found injured, transferred to WWCC and euthanized" | collecting_method == "found injured, transferred to WWCC where euthanized" | collecting_method == "found injured, transferred to WWCC, 'wobbly, lies down often', and euthanized on 2019-08-11" | collecting_method == "gift" | collecting_method == "salavage" | collecting_method == "salbage" | collecting_method == "salvage (caught in Tomahawk trap)" | collecting_method == "salvage" | collecting_method == "salvage (mammal trap)" | collecting_method == "salvaged" | collecting_method == "salvage-hit by vehicle", "salvage", "unknown"))

### Assign known salvage and active
df7 <- df6 %>% 
    mutate(coll_method_7 = ifelse(collecting_method == "dead on road" | collecting_method == "died on barbed wire fence" | collecting_method == "euthanized" | collecting_method == "euthanized while at Wetlands and Wildlife Care Center" | collecting_method == "euthanized while at WWCC" | collecting_method == "found injured and transferred to WWCC where euthanized" | collecting_method == "found injured, transferred to WWCC and euthanized" | collecting_method == "found injured, transferred to WWCC where euthanized" | collecting_method == "found injured, transferred to WWCC, 'wobbly, lies down often', and euthanized on 2019-08-11" | collecting_method == "gift" | collecting_method == "salavage" | collecting_method == "salbage" | collecting_method == "salvage (caught in Tomahawk trap)" | collecting_method == "salvage" | collecting_method == "salvage (mammal trap)" | collecting_method == "salvaged" | collecting_method == "salvage-hit by vehicle", "salvage", ifelse(collecting_method == "feeder trap" | collecting_method == "feeder trap and observational" | collecting_method == "funnel trap" | collecting_method == "mistnet" | collecting_method == "mistnet and observational" | collecting_method == "netted" | collecting_method == "rat trap" | collecting_method == "shot" | collecting_method == "shotgun" | collecting_method == "trap" | collecting_method == "trapped with bow net", "active","unknown")))

### Now build another column, lumping together all coll_methods and assigning as active or salvage
df8 <- df7 %>% mutate(coll_method = ifelse(coll_method_2 == "unknown" & coll_method_3 == "salvage", "salvage", ifelse(coll_method_2 == "unknown" & coll_method_4 == "salvage", "salvage", ifelse(coll_method_2 == "unknown" & coll_method_5 == "salvage","salvage", ifelse(coll_method_2 == "unknown" & coll_method_6 == "salvage", "salvage", ifelse(coll_method_7 == "salvage", "salvage", ifelse(coll_method_7 == "active", "active", "active")))))))


```


```{r}
### make column for genus
library(stringi)
df8$genus <- stri_extract_first_regex(df8$scientific_name, "\\S+")
```


```{r}
### split data frame in two: active dataset and salvage dataset

df_salvage <- df8[which(df8$coll_method == "salvage"),]
df_active <- df8[which(df8$coll_method == "active"),]
```

```{r}
### now count genus and count county for salvage
genus_count<- df_salvage %>% group_by(genus)%>% summarize(count=n()) 
county_count<- df_salvage %>% group_by(county)%>% summarize(count=n())
```
```{r}
### as above, but with proportions/percentages

salvage_data_genus <- df_salvage %>%
  group_by(genus) %>%
  summarise(cnt = n()) %>%
  mutate(freq = round(cnt / sum(cnt), 3))

salvage_data_county <- df_salvage %>%
  group_by(county) %>%
  summarise(cnt = n()) %>%
  mutate(freq = round(cnt / sum(cnt), 3))

active_data_genus <- df_active %>%
  group_by(genus) %>%
  summarise(cnt = n()) %>%
  mutate(freq = round(cnt / sum(cnt), 3))

active_data_county <- df_active %>%
  group_by(county) %>%
  summarise(cnt = n()) %>%
  mutate(freq = round(cnt / sum(cnt), 3))

```


```{r}
### merge datasets together to see how they compare by genus
salvage_active_dataset_genus <-merge(salvage_data_genus, active_data_genus, by.x = "genus", by.y = "genus", all.x = TRUE)

### rename columns for clarity
salvage_active_dataset_genus %>% 
  rename(
    salvage_count = cnt.x,
    active_count = cnt.y, salvage_prop = freq.x, active_prop = freq.y
    )
```

```{r}
salvage_active_dataset_county <-merge(salvage_data_county, active_data_county, by.x = "county", by.y = "county", all.x = TRUE)

### rename columns for clarity
salvage_active_dataset_county %>% 
  rename(
    salvage_count = cnt.x,
    active_count = cnt.y, salvage_prop = freq.x, active_prop = freq.y
    )
```

```{r}
### histogram data

boxplot(salvage_active_dataset_county$cnt.x ~ salvage_active_dataset_county$county)
boxplot(salvage_active_dataset_county$cnt.y ~ salvage_active_dataset_county$county)
```

```{r}
### now same for genus
boxplot(salvage_active_dataset_genus$cnt.x ~ salvage_active_dataset_genus$genus)
boxplot(salvage_active_dataset_genus$cnt.y ~ salvage_active_dataset_genus$genus)
```


```{r}
### now for scatterplots
ggplot(salvage_active_dataset_genus, aes(x=genus, y=cnt.y)) + geom_point(color = "grey33", fill = "darkturquoise", shape = 21, alpha = 0.5, size = 2, stroke = 2)
```


```{r}
ggplot(salvage_active_dataset_genus, aes(x=genus, y=cnt.x)) + geom_point(color = "grey33", fill = "darkturquoise", shape = 21, alpha = 0.5, size = 2, stroke = 2)
```


```{r}
### as above, but for county now
ggplot(salvage_active_dataset_county, aes(x=county, y=cnt.y)) + geom_point(color = "grey33", fill = "darkturquoise", shape = 21, alpha = 0.5, size = 2, stroke = 2)

ggplot(salvage_active_dataset_county, aes(x=county, y=cnt.x)) + geom_point(color = "grey33", fill = "darkturquoise", shape = 21, alpha = 0.5, size = 2, stroke = 2)
```


```{r}
### now time for chi squares, using active percentages as expected values, for genus
observed <- salvage_active_dataset_genus$freq.x
expected <- salvage_active_dataset_genus$freq.y

chisq.test(observed, expected)
```

```{r}
### now time for chi squares, using active percentages as expected values, for county
observed <- salvage_active_dataset_county$freq.x
expected <- salvage_active_dataset_county$freq.y

chisq.test(observed, expected)
```


------------------------------------------------------------------------------------
```{r}
df6$active_salvage <- df6 %>% ifelse(is.na(collecting_method) & coll_method_3 == "salvage", "salvage", 
         ifelse (coll_method_3 == "salvage", "salvage", 
           ifelse (coll_method_5 == "salvage", "salvage", 
             ifelse (coll_method_6 == "salvage", "salvage", 
               ifelse (coll_method_7 == "salvage", "salvage")
               )
             )
           )
         )
       

df7 <- df6 %>% 
    mutate(active_salvage = ifelse(coll_method_3 == "salvage", "salvage", ifelse(coll_method_5 == "salvage", "salvage", ifelse(coll_method_6 == "salvage", "salvage", ifelse(coll_method_7 == "salvage", "salvage", "active")))))

### assigning active_salvage
df5$active_salvae <- df5 %>% 
    ifelse(is.na(collecting_method) & coll_method_3 == "salvage", "salvage", ifelse(collecting_method == "unknown", "salvage", ifelse(collecting_method == "dead on road" | collecting_method == "died on barbed wire fence" | collecting_method == "euthanized" | collecting_method == "euthanized while at Wetlands and Wildlife Care Center" | collecting_method == "euthanized while at WWCC" | collecting_method == "found injured and transferred to WWCC where euthanized" | collecting_method == "found injured, transferred to WWCC and euthanized" | collecting_method == "found injured, transferred to WWCC where euthanized" | collecting_method == "found injured, transferred to WWCC, 'wobbly, lies down often', and euthanized on 2019-08-11" | collecting_method == "gift" | collecting_method == "salavage" | collecting_method == "salbage" | collecting_method == "salvage (caught in Tomahawk trap)" | collecting_method == "salvage" | collecting_method == "salvage (mammal trap)" | collecting_method == "salvaged" | collecting_method == "salvage-hit by vehicle", "salvage", ifelse(coll_method_3 == "salvage", "salvage", ifelse(coll_method_5 == "salvage", "salvage", ifelse(coll_method_6 == "salvage", "salvage", "active"))))))
```



```{r}
df4$coll_method_5 <- ifelse(df4$parts=="tissue" | df4$parts == "tissue; tissue sample" | df4$parts == "wing; tissue", "salvage", 
         ifelse (rem==1, "Friday", 
           ifelse (rem==2, "Saturday", 
             ifelse (rem==3, "Sunday", 
               ifelse (rem==4, "Monday", 
                 ifelse(rem==5, "Tuesday", "Wednesday")
               )
             )
           )
         )
       )

df5 <- df4 %>% 
    filter(is.na(coll_method_3) & coll_method_2 == "unknown") %>%
    mutate(coll_method_6 = ifelse(spec_locality == "Aviary in Oakland" | spec_locality == "aviary of Monica J. Albe, Oakland" | spec_locality == "San Diego Zoo" | spec_locality == "CAPTIVE, San Diego Zoo [probably]" | spec_locality == "CAPTIVE, San Diego Zoo" | spec_locality == "San Francisco Zoo, San Francisco" | spec_locality == "Zoological Society of San Diego" | spec_locality == "Zoological Society of San Diego, CAPTIVE" | spec_locality == "CAPTIVE Zoological Societ of San Diego" | spec_locality == "CAPTIVE Zoological Society of San Diego" | spec_locality == " San Diego: Sea World CAPTIVE" | spec_locality == "Amador High School, 1155 Santa Rita Rd., Pleasanton" | spec_locality == "Pittsburg High School, Pittsburg" | spec_locality == "no specific locality recorded" | spec_locality == "unknown" | spec_locality == "Life Sciences Building courtyard, University of California campus, Berkeley" | spec_locality == "Natural Resources Building, Mineral" | spec_locality == "Outside Earth and Marine Sciences Building, University of California, Santa Cruz" | spec_locality == "near south door of Valley Life Sciences Building, University of California campus, Berkeley" | spec_locality == "near Protein Design Labs (34801 Campus Drive), near Dumbarton Bridge, Fremont" | spec_locality == "W side of Dwinelle Hall, Univ. Calif. campus, Berkeley" | spec_locality == "in vicinity of breezeway between Birge and LeConte Halls, University of California campus, Berkeley" | spec_locality == "Stadium Rim Way between Centennial Rd. and Galey Rd., University of California campus, Berkeley" | spec_locality == "University of California campus, Berkeley" | spec_locality == "University of California Riverside campus, Riverside" | spec_locality == "north side of Hildebrand Hall, University of California campus, Berkeley" | spec_locality == "east side of Lewis Hall, University of California Berkeley campus" |spec_locality == "Unit 2 Dormitory, between Channing and Haste Streets, Berkeley" | spec_locality == "Strawberry Creek Lodge (1320 Addison Street), Berkeley" | spec_locality == "Davis" | spec_locality == "University of California Botanical Garden, Strawberry Canyon, Berkeley" | spec_locality == "Berkeley" | spec_locality == "Life Sciences Addition, University of California, Berkeley" | spec_locality == "Donner Lab, University of California, Berkeley" | spec_locality == "California Hall, University of California, Berkeley" | spec_locality == "Women's Faculty Club, University of California, Berkeley" | spec_locality == "Linsdale Library, Hastings Natural History Reservation" | spec_locality == "San Rafael, 24 Madrona Street" | spec_locality == "San Diego: Sea World CAPTIVE" | spec_locality == "Edwards AFB" | spec_locality == "classroom at Hastings Natural History Reservation" | spec_locality == "labs at Hastings Natural History Reservation, Carmel Valley" | spec_locality == "Lawrence Livermore National Lab" | spec_locality == "outside the Davis Lab, Hastings Natural History Reservation, Carmel Valley" | spec_locality == "Sacramento" | spec_locality == "El Cerrito" | spec_locality == "Ojai" | spec_locality == "Livermore" | spec_locality == "Inverness" | spec_locality == "Bolinas" | spec_locality == "Oakland" | spec_locality == "Pittsburg" | spec_locality == "Pleasant Valley" | spec_locality == "Bethel Island" | spec_locality == "Woodacre" | spec_locality == "Jamesburg" | spec_locality == "Nicasio" | spec_locality == "La Casa de Maria, 801 Ladera Lane, Santa Barbara" | spec_locality == "Anaheim" | spec_locality == "Pt. Mugu Naval Base, Air National Guard hanger" | spec_locality == "Carmel Valley" | spec_locality == "Hopland Research and Extension Center bunkhouse" | spec_locality == "Wildlife Gallery, Bolinas" | spec_locality == "Alameda Naval Station, Alameda" | spec_locality == "Mills College, Oakland", "salvage", 0))
```



```{r}

df4$coll_method_5 <- df4 %>% ifelse(coll_method_2 == "unknown" & is.na(coll_method_3) & parts == "tissue", coll_method_5 == "salvage", ifelse(coll_method_2 == "unknown" & is.na(coll_method_3) & parts == "tissue; tissue sample", coll_method_5 == "salvage", ifelse(coll_method_2 == "unknown" & is.na(coll_method_3) & parts == "wing; tissue", coll_method_5 == "salvage", 0)))

df4$coll_method_5 <- df4 %>% ifelse(coll_method_2 == "unknown" & coll_method_3 == "0" & parts == "tissue", coll_method_5 == "salvage", coll_method_5 =="0")



```







```{r}
### assign coll_method_3 as "salvage" based on collectors "unknown", spec_locality "unknown" or AFB or Campus/School/Building/Zoo/Aviary/Donation/Dormitory/Windown-sill/Captive

df4$coll_method_3 = ifelse(df4$coll_method_2 == "unknown" & is.na(df4$collectors), "salvage", ifelse(df4$coll_method_2 == "unknown" & df4$parts %in% c(grep("^skull\\w*", df4$parts, value=T)), "salvage", ifelse(df4$coll_method_2 == "unknown" & df4$spec_locality %in% c(grep("highway|hwy", df4$spec_locality, ignore.case = T, value = T)),"salvage", ifelse(df4$coll_method_4 == "salvage", "salvage",ifelse(df4$coll_method_2 == "unknown"& df4$collectors== "unknown", "salvage", ifelse(df4$coll_method_2 == "unknown" & df4$spec_locality == '"no specific locality recorded"|"Edwards AFB"|"Vandenberg Air Force Base"', "salvage", ifelse(df4$coll_method_2 == "unknown" & df4$spec_locality == "aviary", "salvage", 0))))))
```



```{r}


### Identify rows that are still of unknown collecting method (i.e., unknown and 0 in coll_method_2 and coll_method_3 columns) as salvage based on address
##First, form new column

Arctos_birds_Calif_2000_2020$coll_method_4[Arctos_birds_Calif_2000_2020$coll_method_2 == "unknown" &
                                             grepl("^[0-9]+", Arctos_birds_Calif_2000_2020$spec_locality, ignore.case = T) &
                                             !grepl(" mi | km | block | m | yds ", Arctos_birds_Calif_2000_2020$spec_locality, 
                                                    ignore.case = T)] = "salvage"  

##Then, sub in coll_meth_3 based on coll_method_4 (i.e., the new column)

Arctos_birds_Calif_2000_2020$coll_method_3<- ifelse(Arctos_birds_Calif_2000_2020$coll_method_4 == "salvage" gsub("0", "salvage", Arctos_birds_Calif_2000_2020$coll_method_3)
Arctos_birds_Calif_2000_2020$coll_method_3 = ifelse(Arctos_birds_Calif_2000_2020$coll_method_2 == "unknown" & is.na(Arctos_birds_Calif_2000_2020$collectors), "salvage", ifelse(Arctos_birds_Calif_2000_2020$coll_method_2 == "unknown" & Arctos_birds_Calif_2000_2020$parts %in% c(grep("^skull\\w*", Arctos_birds_Calif_2000_2020$parts, value=T)), "salvage", ifelse(Arctos_birds_Calif_2000_2020$coll_method_2 == "unknown" & Arctos_birds_Calif_2000_2020$spec_locality %in% c(grep("highway|hwy", Arctos_birds_Calif_2000_2020$spec_locality, ignore.case = T, value = T)),"salvage", ifelse(Arctos_birds_Calif_2000_2020$coll_method_4 == "salvage", "salvage", 0))))
                                                    



```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
