% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{hw\_06}
\author{}
\date{\vspace{-2.5em}}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={hw\_06},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

\#\#1 The data consist of a predictor variable x, plant height, and a
response variable y, grain yield, for eight varieties of rice. \#\#
Consider fitting a simple linear regression model y\_i = \beta\_0 +
\beta\_1x\_i+\varepsilon\_iy , where εi∼iidN(0,σ\^{}2), i = 1, 2,
\ldots, 8

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#data}
\NormalTok{x }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\FloatTok{110.5}\NormalTok{, }\FloatTok{105.4}\NormalTok{, }\FloatTok{118.1}\NormalTok{, }\FloatTok{104.5}\NormalTok{, }\FloatTok{93.6}\NormalTok{, }\FloatTok{84.1}\NormalTok{, }\FloatTok{77.8}\NormalTok{, }\FloatTok{75.6}\NormalTok{)}
\NormalTok{y }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\FloatTok{5.755}\NormalTok{, }\FloatTok{5.939}\NormalTok{, }\FloatTok{6.010}\NormalTok{, }\FloatTok{6.545}\NormalTok{, }\FloatTok{6.730}\NormalTok{, }\FloatTok{6.750}\NormalTok{, }\FloatTok{6.899}\NormalTok{, }\FloatTok{7.862}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{a.-give-the-least-squares-estimate-ux3b21-of-the-slope-_1ux3b21-give-a-brief-interpretation-of-ux3b21}{%
\subsubsection{\texorpdfstring{a. Give the least squares estimate
(\hat{\beta_{1}}β1\^{}) of the slope \beta\_\{1\}β1 Give a brief
interpretation of
\hat{\beta_{1}}β1\^{}}{a. Give the least squares estimate (β1\^{}) of the slope \_\{1\}β1 Give a brief interpretation of β1\^{}}}\label{a.-give-the-least-squares-estimate-ux3b21-of-the-slope-_1ux3b21-give-a-brief-interpretation-of-ux3b21}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{get\_coeff }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(y}\SpecialCharTok{\textasciitilde{}}\NormalTok{x)}
\NormalTok{get\_coeff}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ x)
## 
## Coefficients:
## (Intercept)            x  
##    10.13746     -0.03717
\end{verbatim}

Answer: \^{}B1 = -0.03717; \^{}B1 is the slope of the best fit line,
determining the EXPECTED change in y as x changes

\#\#\#b Perform a test for H\_\{0\}:\beta\emph{\{1\}=0H0 β1=0 versus
H}\{a\}:\beta\_\{1\}\neq0Ha:β1=0 using an F test first and then a T
test. Your conclusion?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(get\_coeff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.34626 -0.27605 -0.09448  0.27023  0.53495 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 10.137455   0.842265  12.036    2e-05 ***
## x           -0.037175   0.008653  -4.296  0.00512 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3624 on 6 degrees of freedom
## Multiple R-squared:  0.7547, Adjusted R-squared:  0.7138 
## F-statistic: 18.46 on 1 and 6 DF,  p-value: 0.005116
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(get\_coeff)}\SpecialCharTok{$}\NormalTok{coefficients[,}\DecValTok{3{-}4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Std. Error   t value     Pr(>|t|)
## (Intercept) 0.842264864 12.035947 1.995872e-05
## x           0.008653462 -4.295933 5.115513e-03
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(get\_coeff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: y
##           Df  Sum Sq Mean Sq F value   Pr(>F)   
## x          1 2.42357 2.42357  18.455 0.005116 **
## Residuals  6 0.78794 0.13132                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Answer: Both t and F-statistic are significant (i.e., p-values
\textless{} 0.05), indicating that this regression model is a good fit
for the data at hand

\hypertarget{c.-construct-a-95-confidence-interval-for-the-intercept-0ux3b20-by-hand-using-the-equation-from-the-lecture-compare-your-results-with-those-from-r-and-briefly-interpret-the-95-confidence-interval.-you-can-get-tn-22tn2ux3b12-using-r-code-qtalpha2-n-2-where-alpha-is-0.05-here.}{%
\subsubsection{\texorpdfstring{c.~Construct a 95\% confidence interval
for the intercept \beta\emph{\{0\}β0 by hand using the equation from the
lecture, compare your results with those from R and briefly interpret
the 95\% confidence interval. You can get t}\{n-2,\alpha/2\}tn−2,α/2
using R code qt(alpha/2, n-2) where alpha is 0.05
here.}{c.~Construct a 95\% confidence interval for the intercept \{0\}β0 by hand using the equation from the lecture, compare your results with those from R and briefly interpret the 95\% confidence interval. You can get t\{n-2,/2\}tn−2,α/2 using R code qt(alpha/2, n-2) where alpha is 0.05 here.}}\label{c.-construct-a-95-confidence-interval-for-the-intercept-0ux3b20-by-hand-using-the-equation-from-the-lecture-compare-your-results-with-those-from-r-and-briefly-interpret-the-95-confidence-interval.-you-can-get-tn-22tn2ux3b12-using-r-code-qtalpha2-n-2-where-alpha-is-0.05-here.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qt}\NormalTok{(}\FloatTok{0.05}\SpecialCharTok{/}\DecValTok{2}\NormalTok{, }\DecValTok{6}\NormalTok{,}\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.446912
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(get\_coeff)}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                Estimate  Std. Error   t value     Pr(>|t|)
## (Intercept) 10.13745532 0.842264864 12.035947 1.995872e-05
## x           -0.03717469 0.008653462 -4.295933 5.115513e-03
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{confint}\NormalTok{(get\_coeff, }\AttributeTok{level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                   2.5 %      97.5 %
## (Intercept)  8.07650745 12.19840320
## x           -0.05834895 -0.01600043
\end{verbatim}

\hypertarget{d.-give-the-fitted-regression-line-as-a-equation-that-looks-like-abxyabx-and-the-raw-residuals.}{%
\subsubsection{\texorpdfstring{d.~Give the fitted regression line (as a
equation that looks like \hat{y}=a+bxy\^{}=a+bx) and the raw
residuals.}{d.~Give the fitted regression line (as a equation that looks like =a+bxy\^{}=a+bx) and the raw residuals.}}\label{d.-give-the-fitted-regression-line-as-a-equation-that-looks-like-abxyabx-and-the-raw-residuals.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(get\_coeff)[}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept) 
##    10.13746
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(get\_coeff)[}\StringTok{"x"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           x 
## -0.03717469
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(get\_coeff)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw_06_files/figure-latex/unnamed-chunk-8-1.pdf} Line: Y
= 10.13746 -0.03717469x

\hypertarget{e.-give-an-estimate-2ux3c32-of-the-error-variance-2ux3c32.}{%
\subsubsection{\texorpdfstring{e. Give an estimate
(\hat{\sigma}\textsuperscript{\{2\}σ}2) of the error variance
(\sigma\^{}\{2\}σ2).}{e. Give an estimate (\{2\}σ2) of the error variance (\^{}\{2\}σ2).}}\label{e.-give-an-estimate-2ux3c32-of-the-error-variance-2ux3c32.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(get\_coeff)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.34626 -0.27605 -0.09448  0.27023  0.53495 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 10.137455   0.842265  12.036    2e-05 ***
## x           -0.037175   0.008653  -4.296  0.00512 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3624 on 6 degrees of freedom
## Multiple R-squared:  0.7547, Adjusted R-squared:  0.7138 
## F-statistic: 18.46 on 1 and 6 DF,  p-value: 0.005116
\end{verbatim}

Answer: estimated standard error for residuals obtained from summary
table above = 0.3624, with 6 degrees of freedom

\hypertarget{f.-estimate-the-expected-yield-of-a-rice-variety-0ux3bc0-that-has-height-x0100x0100-and-provide-a-95-confidence-interval.}{%
\subsubsection{\texorpdfstring{f.~Estimate the expected yield of a rice
variety (\mu\emph{\{0\}μ0) that has height x}\{0\}=100x0=100 and provide
a 95\% confidence
interval.}{f.~Estimate the expected yield of a rice variety (\{0\}μ0) that has height x\{0\}=100x0=100 and provide a 95\% confidence interval.}}\label{f.-estimate-the-expected-yield-of-a-rice-variety-0ux3bc0-that-has-height-x0100x0100-and-provide-a-95-confidence-interval.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(get\_coeff, }\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =} \DecValTok{100}\NormalTok{), }\AttributeTok{interval =} \StringTok{"confidence"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 6.419986 6.096321 6.743651
\end{verbatim}

Answer: 6.419986 , with a lower and upper confidence interval of
6.096321 and 6.723651, respectively \#\#\# g. Predict the yield of a new
rice variety that has height x\_\{0\}=100x 0=100 and provide a 95\%
prediction interval. Compare the results with those from (f), which one
is wider?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(get\_coeff, }\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =} \DecValTok{100}\NormalTok{), }\AttributeTok{interval =} \StringTok{"prediction"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        fit      lwr      upr
## 1 6.419986 5.476038 7.363934
\end{verbatim}

Answer: 6.419986, with a lower and upper prediction interval of 5.476038
and 7.363934, respectively

The prediction intervals are wider, because, in addition to accounting
for the standard error of the mean value (the only error accounted for
by estimating confidence intervals), the prediction intervals must also
account for the error of the predicted value (i.e., prediction intervals
must account for more error than confidence intervals, causing them to
have a wider range)

\hypertarget{h.-compute-the-coefficient-of-determination-r2r2-and-briefly-interpret-what-does-it-mean.}{%
\subsubsection{h. Compute the coefficient of determination R\^{}\{2\}R2
and briefly interpret what does it
mean.}\label{h.-compute-the-coefficient-of-determination-r2r2-and-briefly-interpret-what-does-it-mean.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(get\_coeff)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7546518
\end{verbatim}

Answer: About 75\% of the variance in y (rice yield) is accounted for by
the variance in x (rice height).

\#\#2.This problem is designed to demonstrate why residuals are plotted
against \hat{y}y\^{}(instead of yy). Consider the following (artificial)
data set that was constructed so that the relationship between yy and xx
is quadratic. It is immediately evident that a linear fit is not
appropriate. However, we adopt the point of view that the residual plot
will provide diagnostic information on the lack of fit.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{9}\NormalTok{),}
\AttributeTok{y =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{2.08}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{0.72}\NormalTok{, }\FloatTok{0.28}\NormalTok{, }\FloatTok{0.92}\NormalTok{, }\FloatTok{1.20}\NormalTok{, }\FloatTok{1.12}\NormalTok{, }\FloatTok{0.68}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{0.12}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{1.28}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{a.-plot-yy-vs.-xx.}{%
\subsubsection{a. Plot yy vs.~xx.}\label{a.-plot-yy-vs.-xx.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{x, d}\SpecialCharTok{$}\NormalTok{y)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw_06_files/figure-latex/unnamed-chunk-14-1.pdf}

\hypertarget{b.-plot-the-raw-residuals-vs.-yy.}{%
\subsubsection{b. Plot the raw residuals
vs.~yy.}\label{b.-plot-the-raw-residuals-vs.-yy.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d\_lm\_model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x, }\AttributeTok{data=}\NormalTok{d)}
\NormalTok{d\_lm\_model}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = y ~ x, data = d)
## 
## Coefficients:
## (Intercept)            x  
##        -0.5          0.1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d\_resid }\OtherTok{=} \FunctionTok{resid}\NormalTok{(d\_lm\_model)}
\FunctionTok{plot}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{y, d\_resid)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw_06_files/figure-latex/unnamed-chunk-15-1.pdf}

\hypertarget{c.-plot-the-raw-residuals-vs.-xx.}{%
\subsubsection{c.~Plot the raw residuals
vs.~xx.}\label{c.-plot-the-raw-residuals-vs.-xx.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(d}\SpecialCharTok{$}\NormalTok{x, d\_resid)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw_06_files/figure-latex/unnamed-chunk-16-1.pdf}

P

\hypertarget{d.-lot-the-raw-residuals-vs.-y.}{%
\subsubsection{\texorpdfstring{d.~lot the raw residuals
vs.~\hat{y}y\^{}.}{d.~lot the raw residuals vs.~y\^{}.}}\label{d.-lot-the-raw-residuals-vs.-y.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{fitted}\NormalTok{(d\_lm\_model ), d\_resid)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw_06_files/figure-latex/unnamed-chunk-17-1.pdf}

\hypertarget{e.-compare-the-plots-from-b-c-and-d.-is-there-a-meaningful-difference-between-c-and-d-explain.-which-of-the-plots-b-or-d-gives-a-better-indication-of-the-lack-of-fit-explain.}{%
\subsubsection{e. Compare the plots from (b), (c), and (d). Is there a
meaningful difference between (c) and (d)? Explain. Which of the plots
(b) or (d) gives a better indication of the lack of fit?
Explain.}\label{e.-compare-the-plots-from-b-c-and-d.-is-there-a-meaningful-difference-between-c-and-d-explain.-which-of-the-plots-b-or-d-gives-a-better-indication-of-the-lack-of-fit-explain.}}

Answer: Plots (a), (c), and (d) all show the non-linearity of the data,
while (b) indicates the possibility of a linear relationship. (c) and
(d) differ only in the scale on the x-axis; however, they both still
indicate that a linear model will not fit the data at hand, so this
difference is not very meaningful. Plot (d) gives a better indication of
the lack of fit, due to the plotted data clearly being non-linear (the
data in plot b, however, looks linear, therefore it does not provide
insight into the lack of fit)

\end{document}
